package qweq:maaa

interface hello-world {  // interface
    log: func(param: string)
}

world hello {
    import wasi:clocks/monotonic-clock
    import wasi:clocks/timezone
    import wasi:filesystem/types
    import wasi:sockets/instance-network
    import wasi:sockets/ip-name-lookup
    import wasi:sockets/network
    import wasi:sockets/tcp-create-socket
    import wasi:sockets/tcp
    import wasi:sockets/udp-create-socket
    import wasi:sockets/udp
    import wasi:random/random
    import wasi:random/insecure
    import wasi:random/insecure-seed
    import wasi:poll/poll

    import host: interface {
        log: func(param: string)
    }

    export run: func(a: s32) -> s32
}