package foo:foo

interface math {
  /// Represents a 2D point.
  /// 
  /// # Notes
  /// 1. Not to be confused with a _circle_
  /// 2. Axis `Z` can be assumed to be zero
  record point {
    x: float32,
    y: float32
  }
}

world example {
  /// Translate the point by `dx` horizontally and `dy` vertically
  export move: func(p: point, dx: float32, dy: float32) -> point
}
