name: 'Close stale issues and PRs (stale.yml)'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: >
            This issue has been marked as stale because it has been open for 60 days with no activity.
            It will be closed in 7 days unless there is further activity. To keep it open, add a comment or remove the stale label.

          stale-pr-message: >
            This pull request has been marked as stale because it has been open for 60 days with no activity.
            It will be closed in 10 days unless there is further activity. To keep it open, add a comment or remove the stale label.

          close-issue-message: >
            This issue was closed because it has been inactive for 7 days after being marked as stale.

          close-pr-message: >
            This pull request was closed because it has been inactive for 10 days after being marked as stale.

          days-before-issue-stale: 60
          days-before-pr-stale: 60
          days-before-issue-close: 7
          days-before-pr-close: 10